# Generated by Django 4.1.1 on 2022-10-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_celebrities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrities',
            name='name1',
            field=models.CharField(max_length=250),
        ),
    ]
